name: Build TouchMux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r26d   # latest stable, supports API 33 and 34

      - name: Build TouchMux (arm64, API 33 - Android 13)
        run: |
          mkdir -p bin
          $ANDROID_NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang \
            touchmux.c -O2 -static -o bin/touchmux

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: TouchMux-binary
          path: bin/touchmux
